SELECT c.Name FROM Child c
SELECT * FROM Child
SELECT Happy FROM Child

CREATE TABLE Child (
	ChildId INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	Happy INT NOT NULL
)

CREATE TABLE Toy (
	ToyId INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL,
	ChildId INT NOT NULL,
	FOREIGN KEY (ChildId) REFERENCES Child(ChildId)
)